export const profileConstants = {
    LOAD_PROFILE_DATA: 'LOAD_PROFILE_DATA',
    PROFILE_DATA_SUCCESS: 'PROFILE_DATA_SUCCESS',
    PROFILE_SEARCH_DATA_SUCCESS: 'PROFILE_SEARCH_DATA_SUCCESS',
    PROFILE_DATA_FAILURE: 'PROFILE_DATA_FAILURE',

    PROFILE_DATA_EDIT: 'PROFILE_DATA_EDIT',
    PROFILE_DATA_EDIT_SUCCESS: 'PROFILE_DATA_EDIT_SUCCESS',
    PROFILE_DATA_EDIT_FAILURE: 'PROFILE_DATA_EDIT_FAILURE',

    ONBOARD_PROFILE_DATA: 'ONBOARD_PROFILE_DATA',
    ONBOARD_PROFILE_DATA_SUCCESS: 'ONBOARD_PROFILE_DATA_SUCCESS',
    ONBOARD_PROFILE_DATA_FAILURE: 'ONBOARD_PROFILE_DATA_FAILURE',
};
